StandardRtp:
  #минимальные и максимальные координаты (не меньше 0!)
  xMin: 500
  xMax: 2000
  zMin: 500
  zMax: 2000
  world: "world"
  cooldown: 10
  #мир, где игрок не будет иметь задержку перед телепортацией
  spawnWorld: "world"
  #включить проверку движения при стандартной случайной телепортации
  enableCheckMove: true


  #запрещенные миры, где телепорт нельзя использовать
  worldBlock:
    - "world_nether"


  #настройка групп и их задержек перед телепортацией
  #после "." ставится цифра обозначающая приоритет
  delay:
    default.1: 5
    HOLY.2: 5
    PALADIN.3: 5
    MASTER.4: 5
    GLADIATOR.5: 5
    OVERLORD.6: 5
    ELDER.7: 5
    PHANTOM.8: 0
    KING.9: 0

#создание своих собственных видов
CustomRtp:
  type:
    long:
      xMin: 2000
      xMax: 3000
      zMin: 2000
      zMax: 3000
      world: "world"

    #тут можно добавлять еще

  worldBlock:
    long:
      - "world_nether"

  #настройка групп и их cooldown
  cooldown:

    long:
      default.1: 30
      MASTER.2: 30
      GLADIATOR.3: 30
      OVERLORD.4: 30
      ELDER.5: 30
      PHANTOM.6: 30
      KING.7: 30


RtpPlayer:
  minOnlineInServer: 2
  minDistance: 10
  maxDistance: 110
  cooldown: 60
  tryFoundPlayer: 25

  #миры где не происходит поиск игроков
  worldBlock:
    - "world_nether"

RtpBase:
  minDistance: 2
  maxDistance: 102
  cooldown: 60
  tryFoundBase: 25
  #поиск баз имеет 2 режима
  blockCheck:
    #если включено, то поиск будет только тех баз которые имеют в центре нужные блоки
    enable: true
    regionBlocks:
      - DIAMOND
      - EMERALD_ORE
      - NETHERITE_BLOCK

  #миры, где поиск баз не будет
  worldBlock:
    - "world_nether"


RtpHelpList:
  - "§bПомощь по телепортациям"
  - ""
  - "Стандартная телепортация - §6/rtp"
  - "своя созданная телепортация - §6/rtp <твой вариант>"
  - "Телепортация к безе игроков - §6/rtp base"
  - "Телепортация к случайному игроку - §6/rtp player"


#максимальная высота Y откуда будет происходить поиск локации
MaxY: 120


#количество попыток поиска локации
TryFoundLocation: 25


#неуязвимость после телепортации в секундах
NoDamageTime: 3
blockList:
  - LAVA
  - WATER
  - AIR

