StandardRtp:
  #минимальные и максимальные координаты (не меньше 0!)
  xMin: 500
  xMax: 2000
  zMin: 500
  zMax: 2000
  world: "world"
  cooldown: 10
  #мир, где игрок не будет иметь задержку перед телепортацией
  spawnWorld: "world"
  #включить проверку движения при стандартной случайной телепортации
  enableCheckMove: true


  #запрещенные миры, где телепорт нельзя использовать
  worldBlock:
    - "world_nether"


  #настройка групп и их задержек перед телепортацией
  #после "_" ставится цифра обозначающая приоритет
  delay:
    default_1: 5
    HOLY_2: 5
    PALADIN_3: 5
    MASTER_4: 5
    GLADIATOR_5: 5
    OVERLORD_6: 5
    ELDER_7: 5
    PHANTOM_8: 0
    KING_9: 0

#создание своих собственных видов
CustomRtp:
  type:
    long:
      xMin: 2000
      xMax: 3000
      zMin: 2000
      zMax: 3000
      world: "world"

    #тут можно добавлять еще

  worldBlock:
    long:
      - "world_nether"

  #настройка групп и их cooldown
  cooldown:

    long:
      default_1: 30
      MASTER_2: 30
      GLADIATOR_3: 30
      OVERLORD_4: 30
      ELDER_5: 30
      PHANTOM_6: 30
      KING_7: 30


RtpPlayer:
  minOnlineInServer: 2
  minDistance: 10
  maxDistance: 110
  cooldown: 60
  tryFoundPlayer: 25

  #миры где не происходит поиск игроков
  worldBlock:
    - "world_nether"

RtpBase:
  minDistance: 2
  maxDistance: 102
  cooldown: 60
  tryFoundBase: 25
  #поиск баз имеет 2 режима
  blockCheck:
    #если включено, то поиск будет только тех баз которые имеют в центре нужные блоки
    enable: true
    regionBlocks:
      - DIAMOND
      - EMERALD_ORE
      - NETHERITE_BLOCK

  #миры, где поиск баз не будет
  worldBlock:
    - "world_nether"


RtpHelpList:
  - "§bПомощь по телепортациям"
  - ""
  - "Стандартная телепортация - §6/rtp"
  - "своя созданная телепортация - §6/rtp <твой вариант>"
  - "Телепортация к безе игроков - §6/rtp base"
  - "Телепортация к случайному игроку - §6/rtp player"


#максимальная высота Y откуда будет происходить поиск локации
MaxY: 120


#количество попыток поиска локации
TryFoundLocation: 25


#неуязвимость после телепортации в секундах
NoDamageTime: 3
blockList:
  - LAVA
  - WATER
  - AIR

