StandardRtp:
  xMin: 500
  xMax: 2000
  zMin: 500
  zMax: 2000
  world: "world"
  cooldown: 10
  enableCheckMove: true
  worldBlock:
    - "world_nether"
  delay:
    default: 5
    HOLY: 5
    PALADIN: 5
    MASTER: 5
    GLADIATOR: 5
    OVERLORD: 5
    ELDER: 5
    PHANTOM: 0
    KING: 0


CustomRtp:
  type:
    long:
      xMin: 2000
      xMax: 3000
      zMin: 2000
      zMax: 3000
      world: "world"

  worldBlock:
    long:
      - "world_nether"

  cooldown:
    long:
      default: 30
      MASTER: 30
      GLADIATOR: 30
      OVERLORD: 30
      ELDER: 30
      PHANTOM: 30
      KING: 30

RtpPlayer:
  minOnlineInServer: 2
  minOnlineInWorld: 2
  minDistance: 10
  maxDistance: 110
  cooldown: 60
  worldBlock:
    - "world_nether"

RtpBase:
  minDistance: 2
  maxDistance: 102
  cooldown: 60
  blockCheck:
    enable: true
    regionBlocks:
      - DIAMOND
      - EMERALD
      - NETHERITE_BLOCK
  worldBlock:
    - "world_nether"


RtpHelpList:
  - "§bПомощь по телепортациям"
  - ""
  - "Стандартная телепортация - §6/rtp"
  - "Далекая телепортация - §6/rtp long"
  - "Телепортация к безе игроков - §6/rtp base"
  - "Телепортация к случайному игроку - §6/rtp player"

MaxY: 120
TryFoundLocation: 25
NoDamageTime: 3
blockList:
  - LAVA
  - WATER
  - AIR

