name: HolyWorldRtp
version: '${project.version}'
main: me.galtap.holyworldrtp.HolyWorldRtp
api-version: '1.16'
commands:
  rtp:
    description: команда которая дает доступ к случайным телепортам
softdepend: [WorldGuard, ProtectionStones]
